#!/bin/bash

msgId="991002"

if [ "$1" = "up" ]; then
	pamixer -i 1 -u
	volume=$(pamixer --get-volume-human)
elif [ "$1" = "down" ]; then
	pamixer -d 1 -u
	volume=$(pamixer --get-volume-human)
elif [ "$1" = "toggle" ]; then
	pamixer -t
	volume=$(pamixer --get-volume-human)
fi

dunstify -u low -r "$msgId" "  Volume: $volume"
