#!/usr/bin/env bash

for archivos in ~/.config/style_folder/dracula/*; do
	cp -R "${archivos}" ~/.config/
done

chmod -R +x ~/.config/bspwm/
chmod +x ~/.config/sxhkd/sxhkdrc
chmod -R +x ~/.config/polybar/
chmod -R +x ~/.config/rofi
chmod +x ~/.config/ranger/scope.sh

if [[ "$DESKTOP_SESSION" == 'openbox' ]]; then
  sh ~/.config/polybar/launch.sh
  feh -z --no-fehbg --bg-fill ~/wallpapers/dracula/
  openbox --restart
  betterlockscreen -u ~/wallpapers/dracula/dracula-wall2.png
elif [[ "$DESKTOP_SESSION" == 'bspwm' ]]; then
	bspc wm -r
elif [[ "$DESKTOP_SESSION" == 'i3' ]]; then
	i3-msg restart
fi
